In [ ]:
"""Word-based, Character-Basedm Subword-basedff"""

'Word-based, Character-Basedm Subword-basedff'

In [ ]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
inputs = tokenizer("let's try to tokenize these words")
print(tokenizer.decode(inputs["input_ids"]))

[CLS] let's try to tokenize these words [SEP]


In [ ]:
inputs

{'input_ids': [101, 2292, 1005, 1055, 3046, 2000, 19204, 4697, 2122, 2616, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
inputs = tokenizer("let's try to tokenize these words")
print(tokenizer.decode(inputs["input_ids"]))

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

<s>let's try to tokenize these words</s>


In [ ]:
inputs

{'input_ids': [0, 2716, 18, 860, 7, 19233, 2072, 209, 1617, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

# How to Batch Inputs together

In [ ]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
sentences = [
    "I have been waiting for this course, all my life",
    "I hate this"
]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
print(tokenizer(sentences, padding=True))

{'input_ids': [[101, 1045, 2031, 2042, 3403, 2005, 2023, 2607, 1010, 2035, 2026, 2166, 102], [101, 1045, 5223, 2023, 102, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}


In [ ]:
tokens = [tokenizer.tokenize(sentence) for sentence in sentences]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokens]

print(ids[0])
print(ids[1])

[1045, 2031, 2042, 3403, 2005, 2023, 2607, 1010, 2035, 2026, 2166]
[1045, 5223, 2023]


In [ ]:
#trying to create an araray merging pytensors or numpy arrays will crrate an error, as arrays anf tensors shoulf be rectangular

In [ ]:
import torch
ids = [[1045, 2031, 2042, 3403, 2005, 2023, 2607, 1010, 2035, 2026, 2166],
       [1045, 5223, 2023, 0,0,0,0,0,0,0,0]]

In [ ]:
input_ids = torch.tensor(ids)

In [ ]:
tokenizer.pad_token_id

0

In [ ]:
#we can make a batch with our sentences, after padding them.
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [ ]:
ids1 = torch.tensor([[1045, 2031, 2042, 3403, 2005, 2023, 2607, 1010, 2035, 2026, 2166]])
ids2 = torch.tensor([[1045, 5223, 2023, 0,0,0,0,0,0,0,0]])

In [ ]:
print(model(ids1).logits)
print(model(ids2).logits)
print(model(input_ids).logits)

tensor([[-3.5268,  3.7738]], grad_fn=<AddmmBackward0>)
tensor([[ 1.8737, -1.6813]], grad_fn=<AddmmBackward0>)
tensor([[-3.5268,  3.7738],
        [ 1.8737, -1.6813]], grad_fn=<AddmmBackward0>)


In [ ]:
attention_mask = torch.tensor([[1, 1, 1, 1,1,1,1,1,1,1,1], [1, 1, 1, 0,0,0,0,0,0,0,0]] )

In [ ]:
output = model(input_ids, attention_mask=attention_mask)
output.logits

tensor([[-3.5268,  3.7738],
        [ 3.2110, -2.6103]], grad_fn=<AddmmBackward0>)

In [ ]:
##all of this iss doine behind the scenes if we set padding = true

In [ ]:
print(tokenizer(sentences, padding=True))

{'input_ids': [[101, 1045, 2031, 2042, 3403, 2005, 2023, 2607, 1010, 2035, 2026, 2166, 102], [101, 1045, 5223, 2023, 102, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]]}
